"use strict";

const CANVAS_ID = "game";
const LIGHT_BROWN = "#48483A";
const DARK_BROWN = "#5C574F";
const SOFT_PINK = "#A28F9D";
const ELECTRIC_BLUE = "#1BE7FF";
const MINT_GREEN = "#09BC8A";

export { CANVAS_ID, LIGHT_BROWN, DARK_BROWN, SOFT_PINK, ELECTRIC_BLUE, MINT_GREEN };
